apiVersion: v1
kind: Service
metadata:
  name: abc-manufacturing
  labels:
    app: abc-manufacturing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: abc-manufacturing
